services:
  ingest:
    build: .
    container_name: power-ingest
    volumes:
      - ./:/app
    working_dir: /app
    profiles:
      - ingest
    command: >
      sh -c "python src/dk_holidays.py && 
             python src/day_ahead.py && 
             python src/weather_forecast_meteo.py && 
             python src/wind_solar_load.py"
    # env_file:
    #   - .env

  notebook:
    build: .
    container_name: power-notebook
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./:/app
    working_dir: /app
    command: jupyter lab --ip=0.0.0.0 --allow-root --ServerApp.token=''

    # env_file:
    #   - .env
